/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficos;

/**
 *
 * @author david
 */
public class PanelJuego extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame1
     */
    public PanelJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJuego = new javax.swing.JPanel();
        puntuacionSoles = new javax.swing.JLabel();
        precioLanzaGuisantes = new javax.swing.JLabel();
        precioNuez = new javax.swing.JLabel();
        botonCartaNuez = new javax.swing.JButton();
        precioGirasol = new javax.swing.JLabel();
        botonCartaGirasol = new javax.swing.JButton();
        botonCartaLanzaGuisantes = new javax.swing.JButton();
        casilla11 = new javax.swing.JButton();
        casilla12 = new javax.swing.JButton();
        casilla13 = new javax.swing.JButton();
        casilla14 = new javax.swing.JButton();
        casilla15 = new javax.swing.JButton();
        casilla16 = new javax.swing.JButton();
        casilla17 = new javax.swing.JButton();
        casilla18 = new javax.swing.JButton();
        casilla19 = new javax.swing.JButton();
        casilla21 = new javax.swing.JButton();
        casilla22 = new javax.swing.JButton();
        casilla23 = new javax.swing.JButton();
        casilla24 = new javax.swing.JButton();
        casilla25 = new javax.swing.JButton();
        casilla26 = new javax.swing.JButton();
        casilla27 = new javax.swing.JButton();
        casilla28 = new javax.swing.JButton();
        casilla29 = new javax.swing.JButton();
        casilla31 = new javax.swing.JButton();
        casilla32 = new javax.swing.JButton();
        casilla33 = new javax.swing.JButton();
        casilla34 = new javax.swing.JButton();
        casilla35 = new javax.swing.JButton();
        casilla36 = new javax.swing.JButton();
        casilla37 = new javax.swing.JButton();
        casilla38 = new javax.swing.JButton();
        casilla39 = new javax.swing.JButton();
        casilla41 = new javax.swing.JButton();
        casilla42 = new javax.swing.JButton();
        casilla43 = new javax.swing.JButton();
        casilla44 = new javax.swing.JButton();
        casilla45 = new javax.swing.JButton();
        casilla46 = new javax.swing.JButton();
        casilla47 = new javax.swing.JButton();
        casilla48 = new javax.swing.JButton();
        casilla49 = new javax.swing.JButton();
        casilla51 = new javax.swing.JButton();
        casilla52 = new javax.swing.JButton();
        casilla53 = new javax.swing.JButton();
        casilla54 = new javax.swing.JButton();
        casilla55 = new javax.swing.JButton();
        casilla56 = new javax.swing.JButton();
        casilla57 = new javax.swing.JButton();
        casilla58 = new javax.swing.JButton();
        casilla59 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelJuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        puntuacionSoles.setText("150");
        panelJuego.add(puntuacionSoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        precioLanzaGuisantes.setText("100");
        panelJuego.add(precioLanzaGuisantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        precioNuez.setText("50");
        panelJuego.add(precioNuez, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        botonCartaNuez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/imagenes/cartaNuez.jpg"))); // NOI18N
        botonCartaNuez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCartaNuezActionPerformed(evt);
            }
        });
        panelJuego.add(botonCartaNuez, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 70, 90));

        precioGirasol.setText("50");
        panelJuego.add(precioGirasol, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        botonCartaGirasol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/imagenes/cartaGirasol.jpg"))); // NOI18N
        botonCartaGirasol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCartaGirasolActionPerformed(evt);
            }
        });
        panelJuego.add(botonCartaGirasol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, 90));

        botonCartaLanzaGuisantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/imagenes/cartaLanzaGuisantes.jpg"))); // NOI18N
        botonCartaLanzaGuisantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCartaLanzaGuisantesActionPerformed(evt);
            }
        });
        panelJuego.add(botonCartaLanzaGuisantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 70, 90));

        casilla11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla11ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, 110));

        casilla12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla12ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 100, 110));

        casilla13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla13ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 100, 110));

        casilla14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla14ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 100, 110));

        casilla15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla15ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 100, 110));

        casilla16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla16ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 100, 110));

        casilla17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla17ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla17, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 100, 110));

        casilla18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla18ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla18, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 100, 110));

        casilla19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla19ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla19, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 100, 110));

        casilla21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla21ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 100, 110));

        casilla22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla22ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 100, 110));

        casilla23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla23ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 100, 110));

        casilla24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla24ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 100, 110));

        casilla25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla25ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla25, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 100, 110));

        casilla26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla26ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla26, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 100, 110));

        casilla27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla27ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla27, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 100, 110));

        casilla28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla28ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla28, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 100, 110));

        casilla29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla29ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla29, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 100, 110));

        casilla31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla31ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 100, 110));

        casilla32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla32ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla32, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 100, 110));

        casilla33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla33ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla33, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 100, 110));

        casilla34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla34ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla34, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 100, 110));

        casilla35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla35ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla35, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 100, 110));

        casilla36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla36ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla36, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 100, 110));

        casilla37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla37ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla37, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 100, 110));

        casilla38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla38ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla38, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 100, 110));

        casilla39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla39ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla39, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, 100, 110));

        casilla41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla41ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla41, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 100, 110));

        casilla42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla42ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla42, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 100, 110));

        casilla43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla43ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla43, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 100, 110));

        casilla44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla44ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla44, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 100, 110));

        casilla45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla45ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla45, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 100, 110));

        casilla46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla46ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla46, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 100, 110));

        casilla47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla47ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla47, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 100, 110));

        casilla48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla48ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla48, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 100, 110));

        casilla49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla49ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla49, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 470, 100, 110));

        casilla51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla51ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla51, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 100, 110));

        casilla52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla52ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla52, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 100, 110));

        casilla53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla53ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla53, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 100, 110));

        casilla54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla54ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla54, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 100, 110));

        casilla55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla55ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla55, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 100, 110));

        casilla56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla56ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla56, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 590, 100, 110));

        casilla57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla57ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla57, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 590, 100, 110));

        casilla58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla58ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla58, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 590, 100, 110));

        casilla59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla59ActionPerformed(evt);
            }
        });
        panelJuego.add(casilla59, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 590, 100, 110));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/imagenes/fondo.png"))); // NOI18N
        fondo.setText("150");
        panelJuego.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //############## Cartas ###############
    private void botonCartaNuezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCartaNuezActionPerformed
        // TODO add your handling code here:
        System.out.println("cartaNuez");
    }//GEN-LAST:event_botonCartaNuezActionPerformed

    private void botonCartaGirasolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCartaGirasolActionPerformed
        // TODO add your handling code here:
        System.out.println("cartaGirasol");
    }//GEN-LAST:event_botonCartaGirasolActionPerformed

    private void botonCartaLanzaGuisantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCartaLanzaGuisantesActionPerformed
        // TODO add your handling code here:
        System.out.println("cartaLanzaGuisantes");
    }//GEN-LAST:event_botonCartaLanzaGuisantesActionPerformed
     //############## Termina Cartas ###############
    
    //############## Casillas ###############
    private void casilla11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla11ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla11");
    }//GEN-LAST:event_casilla11ActionPerformed
    
    private void casilla21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla21ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla21");
    }//GEN-LAST:event_casilla21ActionPerformed

    private void casilla31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla31ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla31");
    }//GEN-LAST:event_casilla31ActionPerformed

    private void casilla41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla41ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla41");
    }//GEN-LAST:event_casilla41ActionPerformed

    private void casilla51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla51ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla51");
    }//GEN-LAST:event_casilla51ActionPerformed

    private void casilla12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla12ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla12");
    }//GEN-LAST:event_casilla12ActionPerformed

    private void casilla13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla13ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla13");
    }//GEN-LAST:event_casilla13ActionPerformed

    private void casilla14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla14ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla14");
    }//GEN-LAST:event_casilla14ActionPerformed

    private void casilla15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla15ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla15");
    }//GEN-LAST:event_casilla15ActionPerformed

    private void casilla16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla16ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla16");
    }//GEN-LAST:event_casilla16ActionPerformed

    private void casilla17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla17ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla17");
    }//GEN-LAST:event_casilla17ActionPerformed

    private void casilla18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla18ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla18");
    }//GEN-LAST:event_casilla18ActionPerformed

    private void casilla19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla19ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla19");
    }//GEN-LAST:event_casilla19ActionPerformed

    private void casilla22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla22ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla22");
    }//GEN-LAST:event_casilla22ActionPerformed

    private void casilla23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla23ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla23");
    }//GEN-LAST:event_casilla23ActionPerformed

    private void casilla24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla24ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla24");
    }//GEN-LAST:event_casilla24ActionPerformed

    private void casilla25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla25ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla25");
    }//GEN-LAST:event_casilla25ActionPerformed

    private void casilla26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla26ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla26");
    }//GEN-LAST:event_casilla26ActionPerformed

    private void casilla27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla27ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla27");
    }//GEN-LAST:event_casilla27ActionPerformed

    private void casilla28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla28ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla28");
    }//GEN-LAST:event_casilla28ActionPerformed

    private void casilla29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla29ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla29");
    }//GEN-LAST:event_casilla29ActionPerformed

    private void casilla32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla32ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla32");
    }//GEN-LAST:event_casilla32ActionPerformed

    private void casilla33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla33ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla33");
    }//GEN-LAST:event_casilla33ActionPerformed

    private void casilla34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla34ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla34");
    }//GEN-LAST:event_casilla34ActionPerformed

    private void casilla35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla35ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla35");
    }//GEN-LAST:event_casilla35ActionPerformed

    private void casilla36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla36ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla36");
    }//GEN-LAST:event_casilla36ActionPerformed

    private void casilla37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla37ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla37");
    }//GEN-LAST:event_casilla37ActionPerformed

    private void casilla38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla38ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla38");
    }//GEN-LAST:event_casilla38ActionPerformed

    private void casilla39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla39ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla39");
    }//GEN-LAST:event_casilla39ActionPerformed

    private void casilla42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla42ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla42");
    }//GEN-LAST:event_casilla42ActionPerformed

    private void casilla43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla43ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla43");
    }//GEN-LAST:event_casilla43ActionPerformed

    private void casilla44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla44ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla44");
    }//GEN-LAST:event_casilla44ActionPerformed

    private void casilla45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla45ActionPerformed
        // TODO add your handling code here:
         System.out.println("casilla45");
    }//GEN-LAST:event_casilla45ActionPerformed

    private void casilla46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla46ActionPerformed
        // TODO add your handling code here:
         System.out.println("casilla46");
    }//GEN-LAST:event_casilla46ActionPerformed

    private void casilla47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla47ActionPerformed
        // TODO add your handling code here:
         System.out.println("casilla47");
    }//GEN-LAST:event_casilla47ActionPerformed

    private void casilla48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla48ActionPerformed
        // TODO add your handling code here:
         System.out.println("casilla48");
    }//GEN-LAST:event_casilla48ActionPerformed

    private void casilla49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla49ActionPerformed
        // TODO add your handling code here:
         System.out.println("casilla49");
    }//GEN-LAST:event_casilla49ActionPerformed

    private void casilla52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla52ActionPerformed
        // TODO add your handling code here:
         System.out.println("casilla52");
    }//GEN-LAST:event_casilla52ActionPerformed

    private void casilla53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla53ActionPerformed
        // TODO add your handling code here:
         System.out.println("casilla53");
    }//GEN-LAST:event_casilla53ActionPerformed

    private void casilla54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla54ActionPerformed
        // TODO add your handling code here:
         System.out.println("casilla54");
    }//GEN-LAST:event_casilla54ActionPerformed

    private void casilla55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla55ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla55");
    }//GEN-LAST:event_casilla55ActionPerformed

    private void casilla56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla56ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla56");
    }//GEN-LAST:event_casilla56ActionPerformed

    private void casilla57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla57ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla57");
    }//GEN-LAST:event_casilla57ActionPerformed

    private void casilla58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla58ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla58");
    }//GEN-LAST:event_casilla58ActionPerformed

    private void casilla59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla59ActionPerformed
        // TODO add your handling code here:
        System.out.println("casilla59");
    }//GEN-LAST:event_casilla59ActionPerformed
    //############## Termina Casillas ###############
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {               
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCartaGirasol;
    private javax.swing.JButton botonCartaLanzaGuisantes;
    private javax.swing.JButton botonCartaNuez;
    private javax.swing.JButton casilla11;
    private javax.swing.JButton casilla12;
    private javax.swing.JButton casilla13;
    private javax.swing.JButton casilla14;
    private javax.swing.JButton casilla15;
    private javax.swing.JButton casilla16;
    private javax.swing.JButton casilla17;
    private javax.swing.JButton casilla18;
    private javax.swing.JButton casilla19;
    private javax.swing.JButton casilla21;
    private javax.swing.JButton casilla22;
    private javax.swing.JButton casilla23;
    private javax.swing.JButton casilla24;
    private javax.swing.JButton casilla25;
    private javax.swing.JButton casilla26;
    private javax.swing.JButton casilla27;
    private javax.swing.JButton casilla28;
    private javax.swing.JButton casilla29;
    private javax.swing.JButton casilla31;
    private javax.swing.JButton casilla32;
    private javax.swing.JButton casilla33;
    private javax.swing.JButton casilla34;
    private javax.swing.JButton casilla35;
    private javax.swing.JButton casilla36;
    private javax.swing.JButton casilla37;
    private javax.swing.JButton casilla38;
    private javax.swing.JButton casilla39;
    private javax.swing.JButton casilla41;
    private javax.swing.JButton casilla42;
    private javax.swing.JButton casilla43;
    private javax.swing.JButton casilla44;
    private javax.swing.JButton casilla45;
    private javax.swing.JButton casilla46;
    private javax.swing.JButton casilla47;
    private javax.swing.JButton casilla48;
    private javax.swing.JButton casilla49;
    private javax.swing.JButton casilla51;
    private javax.swing.JButton casilla52;
    private javax.swing.JButton casilla53;
    private javax.swing.JButton casilla54;
    private javax.swing.JButton casilla55;
    private javax.swing.JButton casilla56;
    private javax.swing.JButton casilla57;
    private javax.swing.JButton casilla58;
    private javax.swing.JButton casilla59;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel panelJuego;
    private javax.swing.JLabel precioGirasol;
    private javax.swing.JLabel precioLanzaGuisantes;
    private javax.swing.JLabel precioNuez;
    private javax.swing.JLabel puntuacionSoles;
    // End of variables declaration//GEN-END:variables
}
